-- Private storage buckets for uploaded documents and payment screenshots.
-- No public access and no anon-key policies: all reads/writes happen
-- server-side via the service-role key (signed URLs are generated by the
-- API when the customer or admin needs to view a file).

insert into storage.buckets (id, name, public)
values ('documents', 'documents', false)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('payment-screenshots', 'payment-screenshots', false)
on conflict (id) do nothing;

-- No policies are created for these buckets — default-deny, service role only.
